app:
  title: 'Universe-View'
  version: 'v0.0.1'
  baseUrl: ''
  theme: 'self'
#  看板娘模型选择, 参见: https://github.com/fghrsh/live2d_api
  cute:
    textures: 0
    model: 4
header:
  menu:
    - name: 'title.home'
      path: /index
    - name: 'title.archive'
      path: /hello
    - name: 'title.classify'
      path: /
    - name: 'title.tag'
      path: /
    - name: 'title.audio'
      path: /
    - name: 'title.photo'
      path: /
    - name: 'title.thoughts'
      path: /
    - name: 'title.message'
      path: /
    - name: 'title.about'
      path: /