app:
  title: 'Universe-View'
  version: 'v0.0.1'
  baseUrl: ''
  firstRun: '2021-11-15T17:00:00'
  theme:
    select: base
    needCache: true
  #  看板娘模型选择, 参见: https://github.com/fghrsh/live2d_api
  cute:
    textures: 0
    model: 4
  srcCdn:
    base: https://cdn.jsdelivr.net/gh/leiax00/cdn-for-static
    opts:
      pic: img
  #  svg图片资源, 组件: UvIcon
  srcSvg: //at.alicdn.com/t/font_2015893_qyxz87dt3x.js
header:
  menu:
    - name: 'title.home'
      path: /index
    - name: 'title.archive'
      path: /hello
    - name: 'title.classify'
      path: /
    - name: 'title.tag'
      path: /
    - name: 'title.audio'
      path: /
    - name: 'title.photo'
      path: /
    - name: 'title.thoughts'
      path: /
    - name: 'title.message'
      path: /
    - name: 'title.about'
      path: /

define:
  theme:
    - name: default
      vars:
        --v-theme-color: '#e0e0e0'
        --v-theme-background: '#2f2f2f'
        --v-theme-color-border: '#505050'
        --v-theme-color-hover: '#e91e63'
        --v-theme-header-image: url(https://cdn.jsdelivr.net/gh/leiax00/cdn-for-static/img/bg-load.png)
        --v-theme-margin: 1rem
        --v-theme-padding: 1rem
        --v-theme-nav-height: 4rem
        --v-theme-nav-bgc: rgba(60, 100, 110, 0.6)
        --v-theme-base-font-size: 0.75rem
      responsive:
        xs:
          min: 0
          max: 600
          vars:
            --common-margin: 24px
        sm:
          min: 600
          max: 960
          vars:
        md:
          min: 960
          max: 1280
          vars:
        lg:
          min: 1280
          max: 1920
          vars:
        xl:
          min: 1920
          max: 2560
          vars:
        xxl:
          min: 2560
          max: 10000
          vars:

